# Generated by Django 5.0.6 on 2024-05-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_owner_task_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="owner",
        ),
    ]
